### ISSUE TITLE
Prevent `System.OverflowException`

### ISSUE THREAD

**Issue by TonyTroeff** [TryAtSoftware/Randomizer#39]
Error Message:
   System.OverflowException : Negating the minimum value of a twos complement number is invalid.
  Stack Trace:
     at TryAtSoftware.Randomizer.Core.Helpers.RandomizationHelper.RandomInteger(Int32 inclusiveBottomBound, Int32 exclusiveUpperBound)
   at TryAtSoftware.Randomizer.Core.Helpers.RandomizationHelper.GetRandomStringCombination(Int32 length, IReadOnlyList`1 possibleChars)
   at TryAtSoftware.Randomizer.Core.Helpers.RandomizationHelper.GetRandomString(Int32 length, String charactersMask)
   at TryAtSoftware.Randomizer.Core.Helpers.RandomizationHelper.GetRandomString()

**Comment by TonyTroeff** [comment]
We can use the `RandomNumberGenerator` class. Thus, we will make our code more stable and will fix the current problems.
